package com.example.packagetracker.service;

import com.example.packagetracker.model.Package;
import com.example.packagetracker.repository.PackageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class PackageService {

    @Autowired
    private PackageRepository packageRepository;

    /**
     * Save a new package with validation
     * - Prevents duplicate tracking IDs
     * - Validates that delivery status is not empty
     * - Auto-generates created time (handled by @PrePersist in entity)
     * 
     * @param pkg the package to save
     * @return the saved package
     * @throws IllegalArgumentException if validation fails
     */
    public Package savePackage(Package pkg) {
        // Validate tracking ID
        if (pkg.getTrackingId() == null || pkg.getTrackingId().trim().isEmpty()) {
            throw new IllegalArgumentException("Tracking ID cannot be empty");
        }

        // Prevent duplicate tracking ID
        if (packageRepository.existsByTrackingId(pkg.getTrackingId())) {
            throw new IllegalArgumentException("Tracking ID already exists: " + pkg.getTrackingId());
        }

        // Validate sender name
        if (pkg.getSenderName() == null || pkg.getSenderName().trim().isEmpty()) {
            throw new IllegalArgumentException("Sender name cannot be empty");
        }

        // Validate receiver name
        if (pkg.getReceiverName() == null || pkg.getReceiverName().trim().isEmpty()) {
            throw new IllegalArgumentException("Receiver name cannot be empty");
        }

        // Validate destination city
        if (pkg.getDestinationCity() == null || pkg.getDestinationCity().trim().isEmpty()) {
            throw new IllegalArgumentException("Destination city cannot be empty");
        }

        // Validate delivery status (mandatory)
        if (pkg.getDeliveryStatus() == null || pkg.getDeliveryStatus().trim().isEmpty()) {
            throw new IllegalArgumentException("Delivery status cannot be empty");
        }

        // Validate delivery status values
        String status = pkg.getDeliveryStatus();
        if (!status.equals("Dispatched") && !status.equals("In Transit") && !status.equals("Delivered")) {
            throw new IllegalArgumentException("Invalid delivery status. Must be: Dispatched, In Transit, or Delivered");
        }

        // Save the package (createdTime will be auto-generated by @PrePersist)
        return packageRepository.save(pkg);
    }

    /**
     * Retrieve all packages from the database
     * @return list of all packages
     */
    public List<Package> getAllPackages() {
        return packageRepository.findAll();
    }

    /**
     * Retrieve a package by its tracking ID
     * @param trackingId the tracking ID to search for
     * @return Optional containing the package if found
     */
    public Optional<Package> getPackageByTrackingId(String trackingId) {
        if (trackingId == null || trackingId.trim().isEmpty()) {
            return Optional.empty();
        }
        return packageRepository.findByTrackingId(trackingId);
    }
}
